---
title: "Introduction To R"
format: live-html
editor: 
  markdown: 
    wrap: sentence
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

# Welcome to R!

In this exercise we will introduce you to the data science programming language R.
R is one of the most widely used programming languages in the world for data analysis, with particular strengths in statistical modelling along with data processing and visualisation.

In this walkthrough we'll start by looking at R code in interactive windows in this document, then in the next part we'll get familiar with the most widely used environment for working with R: RStudio; and later we will look at how we can use R to write analysis reports using RMarkdown.

# Part 1: Coding in R

Tradition dictates that when learning to program in a new language, your first task is to print `"Hello World!"` to the console.
Click the `Run Code` button below to take your first step on the way to becoming an R master.

```{webr}
#| autorun: false
print("Hello World!")
```

We've learned out first R command!
To print something to the console, we use the command `print` followed by the message we would like to print, wrapped in quotation marks `""`.
In R, anytime we want to run a command, we always use round brackets `( )` to specify the inputs to our command.
Let's continue our polite introduction with R, and introduce ourselves.
Edit the second print statement below to tell R your name, and click `Run Code` again.

```{webr}
#| autorun: false
print("Hello World!")
print("Hello R, my name is Joe")
```

Now we've got the idea behind print statements, use the code box below to write a print statement, telling R how old you are.

```{webr}
#| autorun: false

```

## Assigning Variables

Just printing things to the console doesn't store them in memory, so R won't actually remember our name or age that we just told it.
We can ask R to remember our information by storing them as variables.

```{webr}
#| autorun: false
name = "Joe"
age = 32
```

Here we've created an object called `name` which we've assigned the value `Joe`, and an object called `age` which we've assigned the value `32`.
Note that R doesn't automatically print out anything to the console when we define objects -- if we want to see their values, we just run the object name.

```{webr}
#| autorun: false
name
age
```

Once we've defined a variable, we can just use its name anytime we want to access it.
To print a combination of static text and variables we've defined, we use the `paste` command

```{webr}
#| autorun: false
paste("Hello R, my name is ", name, " and I am ", age, " years old.")
```

Edit the above values of `name` and `age` to print your full greeting to R.

**Note:** There are two main ways of assigning a value to an object in R, using `=` (i.e. `object = value` like above), or `<-` (i.e. `object <- value`).
There are some minor differences in how these work in some rare situations, however as far as we're concerned both do the same thing.

**Tip:** If you want to assign a variable AND have the value of the variable be printed in the same line, just wrap the line where the variable is created in round brackets `( )`

```{webr}
#| autorun: false
(temperature = 18)
temperature
```

(Note `18` gets printed twice here, one for each line)

Now we've got the formalities out of the way, let's see how we can use R to crunch numbers.

## Using R as a Calculator

R at its most basic form, serves as a calculator.
Use the below window to calculate:

1.  174 + 895

<!-- -->

2.  625 - 481

<!-- -->

3.  72 \* 4

<!-- -->

4.  96 / 12

```{webr}
#| autorun: false
#| 
```

We can also use R for more complex calculations if we need to

```{webr}
#| autorun: false
2 ^ 5 # Raising numbers to a power, e.g. 2 to the power of 5
sin(pi / 2) # Trigonometric functions
log(1000) # Taking logarithms
sqrt(144) # Square roots
```

## Annotating Code

In the code chunk above, note the `#` symbols, followed by a description of what the line does.
This is an example of code annotation, which is a highly recommended practice when writing code, in order to enable someone else (or yourself at a future date) know what the code does/is supposed to do.

In R we add annotations/comments to our code using the `#` symbol.
When R sees a `#` symbol it stops trying to interpret anything after the `#` symbol on the same line as code, meaning we are free to use standard language to describe what is going on, without causing R to do strange things thanks to our choice of words.

It is recommended to include at least one line of comments for each chunk of code you write, although you are free to use more than this if there are important details you feel should be included.
Always err on the side of caution when adding comments, it's a lot better to have to scroll slightly more because the past version of you overexplained something, rather than forgetting or misinterpreting what a piece of code does because past you was overconfident about your memory!

## Variable Types

In introducing ourselves to R, we've actually introduced ourselves to the concept of **variable types**, specifically the `character` type which refers to text, like our `name`; and the `numeric` variable type which refers to numbers, like our `age`.

**Note:** In some other coding languages, the `numeric` type gets broken down further, e.g. into whether the number is a whole number `integer` or a decimal `double`.
While these types exist in R, for almost all practical purposes we never need to worry about the distinction ourselves, and so we can just think of all numbers as being `numeric` type.

The type of a variable determines how it behaves and what we can do with it.
For example we can do standard mathematical operations like addition and multiplication on `numeric` objects, which we can't do with `character` objects.
Conversely, `numeric` objects can only contain numeric digits 0-9, whereas `character` objects can be made up of numbers, letters or special characters.

```{webr}
#| autorun: false
52 + 79
"Hello" * 2
"Hello" + "World!"
```

Defining `character` objects is easy, they are anything that are surrounded by quote marks `""`, so `"Joe"`, "`Nice to meet you`", `"Ant & Dec"` would all be valid character objects in R.
This even applies to numbers if contained in quote marks.
You can check if an object is of type `numeric` using the `is.numeric` command

```{webr}
#| autorun: false
is.numeric(1975)
is.numeric("1975")
```

**Question:** What do you think the command would be to check if an object is of type `character`?
Edit the above code block to check.

**Note:** As you may have noticed from the code chunks so far, we do not need to declare the type of a variable when we create it, R will define the variable type based on what we input.
This is an example of the flexibility that makes R a friendlier language for beginners compared to some other languages, but also means we need to be careful ourselves to make sure that we don't introduce bugs in our code through variables being a different type to what we intend etc.

### Common Pitfalls with R Variables

It's important to know that R is **case sensitive** when it comes to defining variables, and so would consider an object with a name starting with a capital letter to be completely different to that same name all lower case.

Run the below code chunk, and then fix the error.

```{webr}
#| autorun: false
Height = 185 # Height in cemtimetres
height / 2.5 # Convert to inches
```

R executes the code inputted line-by-line, and so we need to make sure to define any variables before we use them.

Run the below code chunk, and then fix the error.

```{webr}
#| autorun: false
height = 1.85 # Height in metres
bmi = weight / (height ^ 2) # Calculate BMI
weight = 80 # Weight in kilos
```

## Working with Vectors

Usually when we're working with data, we'll be dealing with groups of data points rather than just single observations.
To collect values together in R, we use the `c()` command, which stands for `concatenate`, where we include the individual objects we want to combine separated by commas.
The resulting object is often called a vector or a 2D array.

```{webr}
#| autorun: false
names = c("Joe", "Lee", "Sarah", "Lucy", "Ben")
```

We refer to each object in a vector as an **element** of that vector.

**Note:** In R, all elements in a vector have to be of the same variable type.
If we attempt to create a vector containing different variable types, R will convert some of the elements so all the types match.

```{webr}
#| autorun: false
mismatched_data = c("Hello", 4, "Pizza", 0.5)
mismatched_data
```

Note that all of the elements of this vector have quotes `""` around them, indicating they are all now `character` type.
This conversion is done silently (i.e. R won't give an error or a warning when it does this), so it is always worth checking your vector objects in R to make sure everything is the type you expect.

We can extract individual elements from vectors using square brackets `[ ]` with a number corresponding to the position we want to extract, e.g. to extract the 4th element of our `names` vector, we would run

```{webr}
#| autorun: false
names = c("Joe", "Lee", "Sarah", "Lucy", "Ben")
names[4]
```

**Note:** In R, the first element of a vector is in position 1, as opposed to some other languages like Python, where the first element is 0.

We can check how many observations are in a vector using the `length` command

```{webr}
#| autorun: false
length(names)
```

We can create vectors containing sequences of numbers using the `seq` command, which takes three arguments: the number to start at, the number to finish at, and the size of the gaps between the numbers.
So to generate a sequence from 0 to 100 in steps of 5, we would run

```{webr}
#| autorun: false
x = seq(0, 100, 5)
x
```

**Question:** Edit the above code to go from 10 to 140 in steps of 2.
How many numbers are in the resulting sequence?

In a variety of situations, we will want to generate a sequence of numbers which just increase by 1.
There is a handy shortcut for this using a colon `:` which just needs our start and end numbers either side

```{webr}
#| autorun: false
10 : 20
```

We might also want to generate a vector, that is just a given value(s) repeated several times.
To do this, we can use the `rep` command

```{webr}
#| autorun: false
rep("Hello", 7)
rep(0, 10)
```

We can even use `rep` to repeat a vector multiple times.
There are two main cases here: we want to repeat a full vector multiple times, or we want to repeat each element of a vector multiple times.
Run the code chunk below and try to understand how each line works.

```{webr}
#| autorun: false
x = c(1, 2, 3, 4)
rep(x, 3)
rep(x, each = 3)
```

### Summarising Numeric Vectors

R was primarily developed for carrying out statistical analyses, and so as such has a number of in built commands for summarising vectors of numeric data.

- `mean()` – calculating the arithmetic mean of a sample

- `median()` – calculating the median of a sample

- `sd()` – calculating the standard deviation of a sample

- `min()` – the smallest value in a sample

- `max()` – the largest value in a sample

- `IQR()` – the interquartile range of a sample

The code chunk below contains a vector of 12 monthly profits for a company.
Calculate the average (mean) monthly profit, the standard deviation of the profits, as well as the highest and lowest profit.

```{webr}
#| autorun: false
profits = c(100000, 95000, -6000, 25000, 110000, 70000, 
            2000, -10000, 88000, 20000, 25000, 95000)

```

## Working with Data Frames

In addition to usually having multiple observations, it's quite common that our data will contain multiple variables, of which we'll have multiple observations.
In R we encode this information in a **data frame**, a 2 way table where the columns correspond to variables, and rows correspond to the individuals we have data on.
In this course we look to work with data in a **tidy** format, where each row represents a new individual, and each column represents a new variable, and so the number of rows in our data should equal the number of individuals, and the number of columns should equal the number of variables.
Not everyone stores their data in a tidy format, and so it can involve some work pre-processing the data to get it into the tidy format we can work with.

In the majority of situations, we will read data into R from an existing spreadsheet, e.g. a `.csv` file, but we can create them manually using the `data.frame` command.

```{webr}
#| autorun: false
friends = data.frame(
  names = c("Ross", "Joey", "Chandler", "Rachel", "Phoebe", "Monica"),
  ages = c(27, 26, 24, 25, 32, 30),
  male = c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE)
)
friends
```

In this example, we've actually met a third variable type, known as a `logical` or `boolean` object, which can take two values: `TRUE` and `FALSE` (note the all caps, as opposed to `True` and `False` in languages like Python).
We don't need to worry about this too much for now, but will come back to it soon when we want to think about how to extract individuals from our data according to some criteria we're interested in.

We can extract columns from a data frame using `$` syntax, i.e. to extract the `ages` of our friends, we could run

```{webr}
#| autorun: false
friends$ages
```

**Question:** Edit the above code chunk to extract the names from the `friends` data

We can then combine the `$` and `[ ]` notation, to extract specific elements from specific columns.
E.g. to extract the age of the third person

```{webr}
#| autorun: false
friends$ages[3]
```

**Question:** Edit the above code chunk to extract the 5th person's name from the `friends` data frame.

We can find the number of rows and columns in a data frame using the `nrow` and `ncol` respectively, or produce them all at once using `dim`.

```{webr}
#| autorun: false
nrow(friends)
```

Edit the code above to print the number of columns, and then the dimensions of the `friends` data frame.

We can also extract the column names from our data frame as a vector using the `names` command

```{webr}
#| autorun: false
names(friends)
```

A very handy command when working with data frames is the `head` command, which shows you the first few rows of a data frame.
It prints 6 rows by default, although we can specify a different number if we wish through the `n` input

```{webr}
#| autorun: false
# Prints the first 3 row of friends
head(friends, n = 3)
```

It's always recommended to use the `head` command whenever you've loaded or created a new data frame, just to ensure that it looks and is formatted how you're expecting.

## Conditional Statements

Recall the last data type we discovered, the logical or boolean data type, which takes two possible values, `TRUE` and `FALSE`.
As well as being a data type which can exist in our data frames, like the `Male` column in our `friends` data set, we can also generated boolean objects using what are known as conditional statements.
Conditional statements are logical expressions which have two possible answers, TRUE or FALSE, and every input to a conditional statement must give a TRUE or FALSE answer.

Say for example, the statement `10 is greater than 5`.
We represent `greater than` with a `>` symbol, and so we can evaluate this expression in R

```{webr}
#| autorun: false
# Is 10 greater than 5?
10 > 5
```

We see that this expression returns `TRUE`, since 10 is greater than 5.
Conversely, if we ask is `10 less than 5`

```{webr}
#| autorun: false
# Is 10 less than 5?
10 < 5
```

We see that this expression returns `FALSE`, since 10 is not less than 5.
In these examples, we were checking if 10 was strictly greater than or less than 5.
What do you think would happen if we ask if `10 is greater than 10` -- have a think and then run the code chunk to find if you were right.

```{webr}
#| autorun: false
# Is 10 greater than 10?
10 > 10
```

We can check if a value is greater than or equal to another value using the `>=` syntax

```{webr}
#| autorun: false
# Is 10 greater than or equal to 10?
10 >= 10
```

**Question:** Modify the above statement to a statement which checks if a value is less than or equal to another value, and returns `FALSE`.

We can check if two values are equal using the `==` syntax

```{webr}
#| autorun: false
# Does 1 equal 2?
1 == 2
```

And check if things are not equal using the `!=` syntax

```{webr}
#| autorun: false
# Is 9 not equal to 5?
9 != 5
```

We can also check if two character objects are the same.
Try to predict the output for each line before you run the code chunk

```{webr}
#| autorun: false
"Apple" == "Apple"
"Apple" != "Apple"
"Apple" == "apple"
"Apple" != "Apple "
```

So far we've just been looking at conditional expressions using numerical values, but they work exactly the same with predefined variables

```{webr}
#| autorun: false
cost = 500000
budget = 650000
# Have we gone over budget?
cost > budget
# ... relief!
```

**Tip:** When dealing with conditional expressions, the `!` serves as a way to flip `TRUE`s to `FALSE`s and `FALSE`s to `TRUE`s, and so is useful when you want to find out if something is NOT the case, like in the example above where we wanted to see if 9 was NOT equal to 5.
You can do this with any conditional expression, by putting your expression in round brackets `(` `)` and putting an exclamation mark symbol `!` at the front

```{webr}
#| autorun: false
cost > budget # Have we gone over budget?
!(cost > budget) # Have we NOT gone over budget?
```

This may not seem too exciting or useful now, but this is because we've just been evaluating expressions for single objects.
Where conditional expressions really come in handy is when we can evaluate statements using vectors.

Recall the `profits` vector from earlier

```{webr}
#| autorun: false
profits
```

One question we might have is, "Which months did we actually make a profit?" We can see this using conditional expressions

```{webr}
#| autorun: false
profits > 0
```

We see that our output starts `TRUE`, `TRUE`, `FALSE`, indicating that `profits > 0` is `TRUE` for the first two elements (i.e. we made a profit for the first two months) and `FALSE` for the third (i.e. we didn't make a profit in month 3)

We can see which values return `TRUE` for a conditional statement using the `which` command

```{webr}
#| autorun: false
which(profits > 0)
```

This returns a vector of numbers, indicating the position of the `TRUE`s for our statement (in this case, it tells us which months actually had a profit \> 0)

**Question:** Edit the above code chunk to find out which months had a profit of exactly `25000`

### Combining Conditional Expressions

So far we've just looked at conditional expressions which just use a single expression for a single variable.
Often we'll want the answer to more complicated questions, which still have a `TRUE`/`FALSE` answer, but will have more conditions involved.
We can do this using the AND operator `A & B`, which returns `TRUE` if both A and B are `TRUE`, and will return `FALSE` otherwise.

So say for our `profits` vector, we wanted to see the months where we'd made a profit, but the profit was less than `100000`

```{webr}
#| autorun: false
which(profits > 0) # Months where we made a profit
which(profits < 100000) # Months where the profit was less than 100000
which(profits > 0 & profits < 100000) # Months where we made a profit AND it was less than 100000
```

**Question:** Edit the above code chunk to find the months where we made a loss (i.e. `profit < 0`) but the loss was less than 10000 (i.e. `profit > -10000`)

**Note:** When combining conditional expressions, both sides of the operator must be complete conditional expressions in themselves, i.e. both sides of the `&` must evaluate to `TRUE` or `FALSE` in isolation, e.g. if we wanted to see when profits are between 10000 and 20000 we cannot write `profits > 10000 & < 20000` since the right hand side of the `&` isn't a conditional expression, we would need to write `profits > 10000 & profits < 20000`

We can also combine conditional expressions using the OR operator, `A | B`, which returns `TRUE` if A or B (or both) are `TRUE`, and only returns `FALSE` if A and B are both `FALSE`.

Say for our company, it's normal to have a monthly profit of between `20000` and `100000` and we want to find the unusual months where this didn't happen.
We can think of this as a conditional expression, where we want to find the months where profit was less than 20000 or it was greater than 100000.

```{webr}
#| autorun: false
which(profits < 20000) # Months where profit was less than 20000
which(profits > 100000) # Months where the profit was more than 100000
which(profits < 20000 | profits > 100000) # Months where profit was outside the 20-100000 range
```

**Question:** Adjust the above code chunk to see if there were any months where we made more than `100000` in profit, or made a loss of more than `100000`

Inverting conditional expressions using `!` works the same for combined conditional expressions, just wrap the entire combined expression in round brackets `(` `)` and put a `!` at the start

```{webr}
#| autorun: false
which(profits > 20000 & profits < 100000) # Months in the expected range
which(!(profits >= 20000 & profits <= 100000)) # Months NOT in the expected range
```

Note here we've seen two ways to find the the unexpected months, first by using an OR operator `|`, and then by combining an AND operator `&`, with an inversion `!`.

```{webr}
#| autorun: false
which(profits < 20000 | profits > 100000) 
which(!(profits >= 20000 & profits <= 100000))
```

## Missing Values

Data frames are quite flexible, in that the different columns are allowed to be of different variable types (but each column can still only have one variable type), like in the `friends` data frame, we have 1 `character` column, one `numeric` column, and one `boolean` column.
One restriction that is in place on data frames though, is that **all columns must be of the same length** -- i.e. each variable has to have the same number of observations.
This then begs the question -- what do we do if we have some missing information?
Let's say for the `friends` example, we didn't know how old Joey is?
We can encode a missing value in a data frame using `NA`s.
`NA` (standing for Not Available) is how we encode a single piece of missing information.
So, if we didn't know Joey's age, our data frame might look like

```{webr}
#| autorun: false
friends = data.frame(
  names = c("Ross", "Joey", "Chandler", "Rachel", "Phoebe", "Monica"),
  ages = c(27, NA, 24, 25, 32, 30),
  male = c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE)
)
friends
```

`NA`s are actually our fourth variable type, and while they are useful and important, they largely just serve as placeholders for gaps in our data, rather than serving as a variable we can actually do anything with

```{webr}
#| autorun: false
5 + NA
NA + "Hello"
NA / NA
```

There is a final type of 'non-answer' variable type which can arise from some dodgy mathematical calculations, which is `NaN` (standing for Not A Number).
These won't typically be part of a dataset, and instead tend to arise when we try to do something which is mathematically difficult to define

```{webr}
#| autorun: false
0 / 0
Inf - Inf
Inf / Inf
```

## Plotting in R

When working with data, one very common and important task we need to be able to do is to create graphs and plots of our data.
To see plotting in action, we will use one of my favourite datasets, the `penguins` dataset, which gives measurement data on different penguins observed at Palmer Station, Antarctica.
We load the data into our R session using the `data()` command, and then can view the top rows using `head()`.

```{webr}
#| autorun: false

data("penguins")

head(penguins)
```

The data contains: the penguin species (`species`), the island the penguin was found (`island`), the length of the penguin bill (`bill_len`), the depth of the penguin bill (`bill_dep`), the length of the flipper (`flipper_len`) (all lengths in cm), how much the penguin weighs in grams (`body_mass`), the sex of the penguin (`sex`) and the year the penguin was observed (`year`).

Note how some of the entries for the 4th penguin are `NA`, meaning the data is missing (perhaps it was never recorded, or was just lost before it was recorded in this dataset)

To create plots of our data, we can use the `plot` command.
To do this, we give `plot` a number of inputs

- `x` the variable to plot on the x-axis
- `y` the variable to plot on the y-axis
- `main` the heading for our plot
- `xlab` / `ylab` - the axis labels for the x and y axes

For example, to produce a plot of bill length against bill depth, we would run

```{webr}
#| autorun: false

plot(penguins$bill_len, penguins$bill_dep)
```

This produces a scatter plot where each point corresponds to a row (i.e. a penguin) in our data. If we were to comment on this, we would say there appears to be a positive relationship, or positive correlation, between bill length and bill depth -- higher bill lengths are associated with higher bill depths!

**Question** Edit the above command to produce a plot of flipper length against body mass -- what can we say about these variables?

We've made our scatter plot but the labels are a bit rubbish, they're just the names of the R variables, which wouldn't look good in an official document. Fortunately we can set the headings and axis labels to be something much better ourselves, by giving extra inputs to `plot`.

```{webr}
#| autorun: false

plot(penguins$bill_len, penguins$bill_dep,
     main = "Scatter plot of penguin bill length against bill depth",
     xlab = "Bill length (mm)",
     ylab = "Bill depth (mm)")
```

Here the `main` input specifies the heading of the plot, and `xlab`/`ylab` gives the x and y axis labels. 
**Note**: Our headings/labels always need to be given in quotes `"`.

**Question:** Edit your flipper length vs body mass plot to have better headings and axis labels.

What happens if we only give `plot` one variable instead of two?

```{webr}
#| autorun: false

plot(penguins$bill_len)
```

We get a scatter plot just of one variable. Here the y-axis is the bill lengths, and the x-axis is just the row number of the penguin (so the first point on the left corresponds to row 1 of our data, the next one corresponds to row 2 etc)
For plots like this, it's usually better to represent them with a line rather than points, so we can easily see how the variable changes. We can create a line plot by adding the input `type = "l"` to our plot command.

```{webr}
#| autorun: false

plot(penguins$bill_len, type = "l")
```

**Question:** Create a line plot of the penguin body masses. Remember to give your plot a good heading and axis labels!